import { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import {
  CheckCircle2, Circle, Download, Clock, Target
} from 'lucide-react';

interface ChecklistItem {
  id: string;
  task: string;
  timeEstimate: string;
  linkedSection: number | null;
}

interface ChecklistData {
  title: string;
  items: ChecklistItem[];
  footer: string;
}

interface SetupChecklistTrackerProps {
  checklist: ChecklistData;
}

export default function SetupChecklistTracker({ checklist }: SetupChecklistTrackerProps) {
  const [completedTasks, setCompletedTasks] = useState<Set<string>>(() => {
    // Load from cookie
    const saved = document.cookie
      .split('; ')
      .find(row => row.startsWith('setupChecklist='));
    if (saved) {
      try {
        return new Set(JSON.parse(decodeURIComponent(saved.split('=')[1])));
      } catch {
        return new Set();
      }
    }
    return new Set();
  });

  useEffect(() => {
    // Save to cookie (expires in 90 days)
    const expires = new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toUTCString();
    document.cookie = `setupChecklist=${encodeURIComponent(JSON.stringify(Array.from(completedTasks)))}; expires=${expires}; path=/`;
  }, [completedTasks]);

  const toggleTask = (taskId: string) => {
    const newCompleted = new Set(completedTasks);
    if (newCompleted.has(taskId)) {
      newCompleted.delete(taskId);
    } else {
      newCompleted.add(taskId);
    }
    setCompletedTasks(newCompleted);
  };

  const totalTasks = checklist.items.length;
  const totalCompleted = Array.from(completedTasks).length;
  const overallProgress = (totalCompleted / totalTasks) * 100;

  // Calculate total time estimate
  const totalTimeMinutes = checklist.items.reduce((sum, item) => {
    if (item.timeEstimate === 'ongoing') return sum;
    const minutes = parseInt(item.timeEstimate);
    return sum + (isNaN(minutes) ? 0 : minutes);
  }, 0);

  const downloadSetupPlan = () => {
    const content = `${checklist.title}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Progress: ${totalCompleted}/${totalTasks} tasks completed (${overallProgress.toFixed(0)}%)
Total Time Investment: ~${totalTimeMinutes} minutes

Tasks:
${checklist.items.map(item => `${completedTasks.has(item.id) ? '✓' : '○'} ${item.task} (${item.timeEstimate})`).join('\n')}

${checklist.footer}

Generated by Agent Shift - Your AI Orchestration Learning Platform
Generated: ${new Date().toLocaleDateString()}`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'my-setup-checklist.txt';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      {/* Header with Progress */}
      <div className="flex items-center justify-between flex-wrap gap-4">
        <div>
          <h3 className="text-lg font-semibold text-slate-900">{checklist.title}</h3>
          <p className="text-sm text-slate-600">
            Track your setup progress and download your plan
          </p>
        </div>
        <Button
          onClick={downloadSetupPlan}
          variant="outline"
          className="flex items-center gap-2"
        >
          <Download className="h-4 w-4" />
          Download My Plan
        </Button>
      </div>

      {/* Overall Progress Bar */}
      <div className="bg-gradient-to-r from-orange-50 to-amber-50 rounded-lg p-4 border-2 border-orange-200">
        <div className="flex items-center justify-between mb-2">
          <span className="text-sm font-medium text-slate-700">Setup Progress</span>
          <div className="flex items-center gap-3">
            <Badge variant="outline" className="text-orange-700 border-orange-300">
              {totalCompleted}/{totalTasks} completed
            </Badge>
            {totalTimeMinutes > 0 && (
              <span className="text-xs text-slate-600 flex items-center gap-1">
                <Clock className="h-3 w-3" />
                ~{totalTimeMinutes} min total
              </span>
            )}
          </div>
        </div>
        <div className="bg-slate-200 rounded-full h-3">
          <motion.div
            initial={{ width: 0 }}
            animate={{ width: `${overallProgress}%` }}
            transition={{ duration: 0.5 }}
            className="bg-gradient-to-r from-orange-500 to-amber-500 h-3 rounded-full"
          />
        </div>
        {overallProgress === 100 && (
          <motion.p
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            className="text-sm text-green-600 font-medium mt-2 flex items-center gap-2"
          >
            <Target className="h-4 w-4" />
            Congratulations! Your AI orchestration stack is configured!
          </motion.p>
        )}
      </div>

      {/* Checklist Card */}
      <Card className="border-2 border-orange-100 shadow-lg">
        <CardHeader>
          <CardTitle className="text-xl flex items-center gap-2">
            <div className="h-10 w-10 bg-gradient-to-br from-orange-500 to-amber-500 rounded-lg flex items-center justify-center">
              <CheckCircle2 className="h-6 w-6 text-white" />
            </div>
            Setup Tasks
          </CardTitle>
          <CardDescription className="text-base">
            Complete each step to configure your first AI agent
          </CardDescription>
        </CardHeader>

        <CardContent className="space-y-3">
          {/* Tasks Checklist */}
          {checklist.items.map((item) => {
            const isCompleted = completedTasks.has(item.id);
            return (
              <button
                key={item.id}
                onClick={() => toggleTask(item.id)}
                className="w-full text-left p-4 rounded-lg border-2 border-slate-200 hover:border-orange-300 hover:bg-orange-50/50 transition-all flex items-start gap-3 group"
              >
                <div className="flex-shrink-0 mt-0.5">
                  {isCompleted ? (
                    <CheckCircle2 className="h-5 w-5 text-green-500" />
                  ) : (
                    <Circle className="h-5 w-5 text-slate-300 group-hover:text-orange-400" />
                  )}
                </div>
                <div className="flex-1">
                  <span className={`block ${isCompleted ? 'text-slate-500 line-through' : 'text-slate-700 font-medium'}`}>
                    {item.task}
                  </span>
                  <div className="flex items-center gap-2 mt-1">
                    <span className="text-xs text-slate-500 flex items-center gap-1">
                      <Clock className="h-3 w-3" />
                      {item.timeEstimate}
                    </span>
                    {item.linkedSection !== null && (
                      <Badge variant="outline" className="text-xs">
                        Section {item.linkedSection}
                      </Badge>
                    )}
                  </div>
                </div>
              </button>
            );
          })}
        </CardContent>
      </Card>

      {/* Footer */}
      <div className="bg-slate-100 rounded-lg p-4 text-sm text-slate-700 border-l-4 border-orange-500">
        <p>{checklist.footer}</p>
      </div>

      {/* Completion Celebration */}
      {overallProgress === 100 && (
        <motion.div
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          className="bg-gradient-to-r from-green-500 to-teal-500 text-white p-6 rounded-lg shadow-lg"
        >
          <div className="flex flex-col md:flex-row items-center md:items-start gap-4 text-center md:text-left">
            <CheckCircle2 className="h-8 w-8 flex-shrink-0" />
            <div className="w-full">
              <h3 className="text-xl font-bold mb-2">Setup Complete!</h3>
              <p className="mb-3 opacity-95">
                You've completed all setup tasks. Your AI orchestration stack is ready to use!
              </p>
              <p className="text-sm opacity-90">
                <strong>Next Step:</strong> Head to the Mindset tab to start implementing your first orchestrated workflow.
              </p>
            </div>
          </div>
        </motion.div>
      )}
    </div>
  );
}
