import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Copy, FileText, Download } from "lucide-react";

interface CalculationResult {
  timeSavedPerTask: number;
  tasksPerWeek: number;
  totalWeeklySavings: number;
  totalAnnualHours: number;
  dollarValue: number;
  breakEvenWeeks: number;
}

interface PurchaseRequestBuilderProps {
  result: CalculationResult | null;
  taskType: string;
  taskPresets: Record<string, { name: string; manual: number; ai: number; savings: number }>;
}

export function PurchaseRequestBuilder({ result, taskType, taskPresets }: PurchaseRequestBuilderProps) {
  const preset = taskType ? taskPresets[taskType as keyof typeof taskPresets] : null;

  const generateTemplate = () => {
    if (!result || !preset) return "Please calculate ROI first using the calculator above.";

    return `
AI TOOL PURCHASE REQUEST

1. EXECUTIVE SUMMARY
Request: ${preset.name} Automation Tool
Annual Net Value: $${result.dollarValue.toFixed(0).replace(/\B(?=(\d{3})+(?!\d))/g, ",")}
Break-Even Period: ${result.breakEvenWeeks < 1 ? "Less than 1 week" : `${result.breakEvenWeeks.toFixed(1)} weeks`}
Recommendation: Approve for 90-day pilot

2. BUSINESS NEED
Current Process: ${preset.name} tasks consume ${result.totalWeeklySavings.toFixed(1)} hours per week of staff time
Impact: ${(result.totalAnnualHours / 8).toFixed(0)} full workdays annually spent on routine tasks
Opportunity: AI automation can reduce task time by ${preset.savings}% while maintaining or improving quality

3. PROPOSED SOLUTION
Tool Category: Enterprise AI Assistant with ${preset.name.toLowerCase()} capabilities
Compliance: FedRAMP, SOC 2, HIPAA certified options available
Deployment: Cloud-based SaaS with enterprise security controls
Training: Self-service onboarding (30-minute learning curve)

4. COST-BENEFIT ANALYSIS
Annual Tool Cost: $240 (typical $20/month subscription)
Annual Time Savings Value: $${(result.dollarValue + 240).toFixed(0).replace(/\B(?=(\d{3})+(?!\d))/g, ",")}
Net Annual Value: $${result.dollarValue.toFixed(0).replace(/\B(?=(\d{3})+(?!\d))/g, ",")}
ROI: ${((result.dollarValue / 240) * 100).toFixed(0)}%

Time Savings Breakdown:
- Per Task: ${result.timeSavedPerTask.toFixed(0)} minutes saved
- Weekly: ${result.totalWeeklySavings.toFixed(1)} hours reclaimed
- Annually: ${result.totalAnnualHours.toFixed(0)} hours (${(result.totalAnnualHours / 8).toFixed(0)} workdays)

5. RISK MITIGATION
Security: Enterprise versions meet federal compliance standards (FedRAMP, CJIS)
Data Privacy: On-premise deployment options available; no training on customer data
Vendor Stability: Backed by major investors with proven enterprise customer base
Technical Risk: 90-day pilot allows validation before full commitment
Exit Strategy: No long-term contract required; data export capability

6. ALTERNATIVES CONSIDERED
Do Nothing: Cost = $${(result.dollarValue + 240).toFixed(0)} annual opportunity loss
Platform Bundle (Microsoft 365 Copilot): Higher cost ($30-60/user), ecosystem lock-in
Recommended Approach (Best-of-Breed): Optimal cost-performance ratio, flexibility

7. IMPLEMENTATION PLAN
Week 1-2: Pilot with 3-5 users on actual work tasks
Week 3-4: Measure time savings, quality, user satisfaction
Month 2: Scale to full team based on pilot results
Month 3: Full deployment and training completion

8. SUCCESS METRICS
Quantitative: Achieve 60%+ time savings on target tasks within 30 days
Qualitative: User satisfaction rating 4/5 or higher
Financial: Break even within ${result.breakEvenWeeks.toFixed(0)} weeks

9. RECOMMENDATION
Approve $240 annual subscription for 90-day pilot program.
Expected return: $${result.dollarValue.toFixed(0)} net annual value after achieving full adoption.

10. APPROVAL REQUIRED
Budget Authority: $240/year ongoing operational expense
Timeline: Immediate start to capture Q1 productivity gains

Research Citations:
- McKinsey: 60-70% of work activities can be automated (2023)
- Stanford/MIT: 34% productivity increase for less-skilled workers (NBER Working Paper)
- Google Cloud Study: 171% average ROI, 74% achieve ROI in year 1 (2025)

Generated by: AI Agent Portal Business Case Calculator
Date: ${new Date().toLocaleDateString()}
    `.trim();
  };

  const copyTemplate = () => {
    const template = generateTemplate();
    navigator.clipboard.writeText(template);
  };

  return (
    <div className="space-y-6">
      <Card className="border-chart-2/20">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FileText className="h-5 w-5" />
            Auto-Generated Purchase Request
          </CardTitle>
          <CardDescription>
            {result ? "Based on your ROI calculation" : "Calculate ROI above to generate your template"}
          </CardDescription>
        </CardHeader>
        <CardContent>
          {result && preset ? (
            <div className="space-y-4">
              <div className="bg-slate-50 p-4 rounded-lg border border-slate-200 max-h-96 overflow-y-auto">
                <pre className="text-xs font-mono text-slate-700 whitespace-pre-wrap">
                  {generateTemplate()}
                </pre>
              </div>
              <div className="flex gap-3">
                <Button onClick={copyTemplate} className="flex-1" variant="default">
                  <Copy className="h-4 w-4 mr-2" />
                  Copy to Clipboard
                </Button>
                <Button variant="outline" className="flex-1">
                  <Download className="h-4 w-4 mr-2" />
                  Download as Word Doc
                </Button>
              </div>
              <p className="text-xs text-slate-600 text-center">
                Copy and paste into your organization's purchase request system, or download as a formatted document
              </p>
            </div>
          ) : (
            <div className="text-center py-8 text-slate-600">
              <FileText className="h-12 w-12 mx-auto mb-3 text-slate-300" />
              <p>Calculate your ROI using the calculator above to generate a customized purchase request template.</p>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Key Sections Guide */}
      <Card className="border-accent/20">
        <CardHeader>
          <CardTitle className="text-lg">What's Included in the Template</CardTitle>
        </CardHeader>
        <CardContent className="space-y-3 text-sm">
          <div>
            <strong className="text-slate-900">Executive Summary:</strong>
            <span className="text-slate-600"> One-page overview with key metrics for decision-makers who won't read the full document</span>
          </div>
          <div>
            <strong className="text-slate-900">Cost-Benefit Analysis:</strong>
            <span className="text-slate-600"> ROI calculation with your actual numbers, showing break-even timeline and annual value</span>
          </div>
          <div>
            <strong className="text-slate-900">Risk Mitigation:</strong>
            <span className="text-slate-600"> Addresses security, compliance, vendor stability, and exit strategy concerns</span>
          </div>
          <div>
            <strong className="text-slate-900">Alternatives Considered:</strong>
            <span className="text-slate-600"> Shows due diligence by comparing platform bundles vs. best-of-breed approaches</span>
          </div>
          <div>
            <strong className="text-slate-900">Implementation Plan:</strong>
            <span className="text-slate-600"> 90-day pilot approach with clear milestones and success metrics</span>
          </div>
          <div>
            <strong className="text-slate-900">Research Citations:</strong>
            <span className="text-slate-600"> Backed by peer-reviewed studies from McKinsey, Stanford, MIT, and Google Cloud</span>
          </div>
        </CardContent>
      </Card>

      {/* Tips Card */}
      <Card className="bg-gradient-to-br from-chart-2/5 to-chart-5/5 border-chart-2/20">
        <CardContent className="pt-6">
          <h4 className="font-semibold text-slate-900 mb-3">Pro Tips for Purchase Requests:</h4>
          <ul className="space-y-2 text-sm text-slate-700">
            <li className="flex items-start gap-2">
              <span className="text-chart-2 font-bold">•</span>
              <span><strong>Lead with the break-even time.</strong> Decision-makers care most about how fast this pays for itself.</span>
            </li>
            <li className="flex items-start gap-2">
              <span className="text-chart-2 font-bold">•</span>
              <span><strong>Propose a pilot, not a commitment.</strong> 90 days reduces risk and gets faster approval.</span>
            </li>
            <li className="flex items-start gap-2">
              <span className="text-chart-2 font-bold">•</span>
              <span><strong>Address compliance proactively.</strong> Security teams will ask - beat them to it.</span>
            </li>
            <li className="flex items-start gap-2">
              <span className="text-chart-2 font-bold">•</span>
              <span><strong>Show you considered alternatives.</strong> "Do nothing" and "platform bundle" comparisons prove you did your homework.</span>
            </li>
          </ul>
        </CardContent>
      </Card>
    </div>
  );
}
